# encoding: utf-8

require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

properties = YAML.load_file('properties.yml')
# TODO : check why serverspec:all doesn't run all test, otherwise one single test is ran.
desc "Run serverspec to all hosts"
task :spec => 'serverspec:all'
task :default => :spec 

namespace :serverspec do
  task :all => properties.keys.map { |fqdn| 'serverspec:' + fqdn.split('.')[0] }
  properties.keys.each do |host|
    desc "Run serverspec to #{host}"
	RSpec::Core::RakeTask.new(host.split('.')[0].to_sym) do |t|
      ENV['TARGET_HOST'] = host
	  t.pattern = 'spec/{' + properties[host][:roles].join(',') + '}/*_spec.rb'
    end
  end
end

